---
- name: Create Grafana directory tree
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: 472
    group: 472
    mode: "0755"
  loop:
    - "{{ grafana_data_path | dirname }}"
    - "{{ grafana_data_path }}"
    - "{{ grafana_data_path }}/dashboards"
    - "{{ grafana_data_path }}/provisioning/datasources"
    - "{{ grafana_data_path }}/provisioning/dashboards"

- name: Provision Grafana dashboards and datasources
  when: inventory_hostname in groups['mntr']
  block:
    - name: Copy Grafana datasources provisioning
      ansible.builtin.copy:
        src: provisioning/datasources/datasources.yml
        dest: "{{ grafana_data_path }}/provisioning/datasources/datasources.yml"
        owner: 472
        group: 472
        mode: "0644"

    - name: Copy Grafana dashboards provisioning
      ansible.builtin.copy:
        src: provisioning/dashboards/dashboards.yml
        dest: "{{ grafana_data_path }}/provisioning/dashboards/dashboards.yml"
        owner: 472
        group: 472
        mode: "0644"

    - name: Copy Grafana dashboard JSON files with subfolders
      ansible.builtin.copy:
        src: dashboards/
        dest: "{{ grafana_data_path }}/dashboards/"
        owner: "472"
        group: "472"
        mode: "0644"

- name: Deploy Grafana stack
  ansible.builtin.include_role:
    name: deploy_docker_stack
  vars:
    stack_name: grafana
    stack_compose_path: "{{ grafana_data_path }}/compose.yml"
