---
- name: Create LGTM and Prometheus directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - "{{ prometheus_data_path | dirname }}"
    - "{{ prometheus_data_path }}"
    - "{{ prometheus_data_path }}/rules"

- name: Generate Prometheus config
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_data_path }}/config.yml"
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname in groups['mntr']

- name: Generate Prometheus alert rules
  ansible.builtin.template:
    src: rules.yml.j2
    dest: "{{ prometheus_data_path }}/rules/alerts.yml"
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname in groups['mntr']

- name: Deploy Prometheus stack
  ansible.builtin.include_role:
    name: deploy-docker-stack
  vars:
    stack_name: prometheus
    stack_compose_path: "{{ prometheus_data_path }}/compose.yml"
