---
- name: Set system hostname
  ansible.builtin.hostname:
    name: "{{ set_hostname_name }}"
    use: systemd
  when: ansible_facts.hostname != set_hostname_name

- name: Ensure localhost hostname mapping in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ set_hostname_name }}"
    state: present
