---
- name: Run gitlab-ctl reconfigure
  ansible.builtin.command:
    cmd: gitlab-ctl reconfigure
  when: inventory_hostname in groups['cicd']

- name: Restart gitlab-runner
  ansible.builtin.systemd:
    name: gitlab-runner
    state: restarted
    enabled: true
  when: inventory_hostname in groups['cicd']
