---
- name: Base OS Hardening and Prerequisites Setup
  hosts: all
  gather_facts: true
  roles:
    - role: set_netplan
    - role: set_hostname
    - role: set_timezone
    - role: set_repository
      when:
        - set_repository_apt_urls | default([]) | length > 0
        - set_repository_repositories | default([]) | length > 0
    - role: set_packages
    - role: set_users
    - role: set_firewall
      vars:
        set_firewall_ssh_port: "{{ ssh_port }}"
    - role: set_ssh
      vars:
        set_ssh_port: "{{ ssh_port }}"
    - role: set_motd
