- name: Initialize Docker Swarm
  hosts: all
  gather_facts: true
  roles:
    - role: set_docker_swarm

- name: Create Docker overlay networks
  hosts: swarm_managers
  gather_facts: false
  roles:
    - role: set_docker_network
