---
- name: Deploy monitoring agents on all nodes
  hosts: all
  gather_facts: true
  roles:
    - role: deploy-node-exporter
    - role: deploy-promtail

- name: Deploy LGTM stack on monitoring node
  hosts: mntr
  gather_facts: true
  roles:
    - role: deploy-grafana
    - role: deploy-prometheus
    - role: deploy-alertmanager
    - role: deploy-loki
    - role: deploy-tempo

- name: Deploy cAdvisor from Swarm manager
  hosts: mgmt
  gather_facts: false
  roles:
    - role: deploy-cadvisor
    - role: deploy-nginx-exporter
