---
- name: Deploy Standalone GitLab
  hosts: cicd
  gather_facts: true
  roles:
    - role: deploy-gitlab-standalone

- name: Deploy GitLab Runner for Docker Buildx
  hosts: cicd
  gather_facts: true
  roles:
    - role: deploy-gitlab-runner
