---
- name: Create Nexus directories on target node
  ansible.builtin.file:
    path: "{{ nexus_data_path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy Nexus stack
  ansible.builtin.include_role:
    name: deploy_docker_stack
  vars:
    stack_name: nexus
    stack_compose_path: "{{ nexus_data_path }}/compose.yml"
