---
- name: Configure APT repositories
  ansible.builtin.deb822_repository:
    name: custom-repo
    types: deb
    uris: "{{ set_repository_apt_urls }}"
    suites: "{{ set_repository_repositories }}"
    components:
      - main
      - universe
    state: present
  when:
    - set_repository_apt_urls | length > 0
    - set_repository_repositories | length > 0
  notify: Update APT cache
