---
- name: Install prerequisites
  ansible.builtin.import_tasks: prerequisites.yml

- name: Configure Docker APT repository
  ansible.builtin.import_tasks: repository.yml

- name: Install Docker Engine
  ansible.builtin.import_tasks: install.yml

- name: Configure Docker daemon
  ansible.builtin.import_tasks: configure.yml

- name: Configure Docker registry authentication
  ansible.builtin.import_tasks: registry_auth.yml
  when:
    - set_docker_deploy | length > 0
    - set_docker_registries | length > 0
    - set_docker_username | length > 0
    - set_docker_password | length > 0
