---
- name: Create user groups
  ansible.builtin.import_tasks: groups.yml

- name: Create user accounts
  ansible.builtin.import_tasks: users.yml

- name: Configure sudo access
  ansible.builtin.import_tasks: sudo.yml

- name: Manage SSH authorized keys
  ansible.builtin.import_tasks: ssh_keys.yml
