---
- name: Deploy Swarm firewall rules
  ansible.builtin.import_tasks: firewall.yml

- name: Initialize Docker Swarm
  ansible.builtin.import_tasks: init.yml

- name: Distribute Swarm join tokens
  ansible.builtin.import_tasks: tokens.yml

- name: Join nodes to Swarm cluster
  ansible.builtin.import_tasks: join.yml
