---
- name: Remove default MOTD scripts
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ set_motd_remove_scripts }}"

- name: Deploy custom MOTD script
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/update-motd.d/01-custom
    mode: "0755"
