---
- name: Create Loki directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - "{{ loki_data_path | dirname }}"
    - "{{ loki_data_path }}"

- name: Generate Loki config
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ loki_data_path }}/config.yml"
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname in groups['mntr']

- name: Deploy Loki stack
  ansible.builtin.include_role:
    name: deploy-docker-stack
  vars:
    stack_name: loki
    stack_compose_path: "{{ loki_data_path }}/compose.yml"
