---
# === Users ===
sudo_users:
  - name: dauxdu
    ssh_public_key: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ9pqriGF4LIh513DwUZEIbhdhekefLD6Z1wS7F7Sp0M vsfi-dauxdu
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEOGmVpn7RAatSVvctYDrWkCEFPU3CeQoswqIIPzF/U9
  - name: nikitaslipenchuk
    ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHwzuTrxNLxECMBKNA5Or3DfjoShBZjL1J4yrZ0LsYhp vsfi-nikitaslipenchuk"
  - name: RidRapsody
    ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGJjhXUlwEqNuuQu/tDjIEYrV55BeToABnXLVAPE3DEn vsfi-RidRapsody"
  - name: quuuqq11
    ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICh/N1TLwCkH7BZ649lzSkKAzkDTlxw3x7GviFej9suU vsfi-quuuqq11"
  - name: Kosta110606
    ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDay47CbtpZSapnbZBitFs1sAgNkaHC8i8JoWrKbYx3P vsfi-Kosta110606"

deploy_users:
  - name: deployer
    ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA9SeNAhdyLbRJzqmHm2oWRu3auNLLjfJ1Xo+xnn4kNx vsfi-deployer"

# === Firewall ===
ssh_port: 22

# === Domain ===
domain: "vsfi.team"
subdomain: "team01"
fulldomain: "{{ subdomain }}.{{ domain }}"

# === Docker ===
docker_registries:
  - "registry.{{ fulldomain }}"
docker_username: gitlab-ci
docker_password: "{{ vault_docker_password }}"

docker_overlay_networks:
  - name: traefik-public
    encrypted: false
  - name: grafana-internal
    encrypted: true
    internal: true
  - name: postgres-internal
    encrypted: true
    internal: true
  - name: frontend-internal
    encrypted: true
    internal: true
  - name: backend-internal
    encrypted: true
    internal: true

# === Vault ===
vault_domain: "vault.{{ fulldomain }}"
vault_allowed_domain: "{{ fulldomain }}"

# === Portainer ===
portainer_domain: "prt.{{ fulldomain }}"

# === PostgreSQL ===
postgres_password: "{{ vault_postgres_password }}"

# === Keycloak ===
keycloak_db: "keycloak"
keycloak_db_user: "keycloak"
keycloak_db_password: "{{ vault_keycloak_db_password }}"
keycloak_domain: "auth.{{ fulldomain }}"
keycloak_realm_name: "vsfi"
keycloak_admin_user: "dauxdu"
keycloak_admin_password: "{{ vault_keycloak_admin_password }}"
keycloak_realm_admin_users:
  - dauxdu
  - nikitaslipenchuk
keycloak_realm_editor_users:
  - RidRapsody
keycloak_realm_viewer_users:
  - quuuqq11
  - Kosta110606

# === Grafana OAuth ===
grafana_oauth_id: "grafana-oauth"
grafana_oauth_secret: "{{ vault_grafana_oauth_secret }}"
grafana_domain: "gr.{{ fulldomain }}"

# === LGTM ===
prometheus_domain: "prom.{{ fulldomain }}"
loki_domain: "loki.{{ fulldomain }}"
tempo_domain: "tempo.{{ fulldomain }}"

# === Alertmanager ===
alertmanager_domain: "alert.{{ fulldomain }}"
telegram_bot_token: "{{ vault_telegram_bot_token }}"
telegram_chat_id: 536988073

# === GitLab ===
gitlab_domain: "git.{{ fulldomain }}"
gitlab_root_password: "{{ vault_gitlab_root_password }}"
gitlab_runner_token: "{{ vault_gitlab_runner_token }}"

# === RustFS / S3 ===
rustfs_domain: "s3.{{ fulldomain }}"
rustfs_user: "dauxdu"
rustfs_password: "{{ vault_rustfs_password }}"
s3_endpoint: "https://{{ rustfs_domain }}"
s3_bucket: "postgres-backups"
s3_access_key: "{{ rustfs_user }}"
s3_secret_key: "{{ rustfs_password }}"

# === Nexus ===
nexus_domain: "nexus.{{ fulldomain }}"
nexus_registry_domain: "registry.{{ fulldomain }}"

# === Backup ===
backup_encryption_key: "{{ vault_backup_encryption_key }}"
backup_databases:
  - "{{ keycloak_db }}"
