---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: dauxdu
    ansible_ssh_private_key_file: "~/.ssh/vsfi-dauxdu"

    network_interface: "ens18"
    dhcp: false
    subnet_mask: "24"
    gateway: "10.0.8.1"
    dns_servers:
      - 10.0.8.1
      - 10.0.8.5

  children:
    mgmt:
      hosts:
        mgmt1:
          ansible_host: 10.0.8.20
          ip_address: "10.0.8.20"

    cicd:
      hosts:
        cicd1:
          ansible_host: 10.0.8.21
          ip_address: "10.0.8.21"

    mntr:
      hosts:
        mntr1:
          ansible_host: 10.0.8.22
          ip_address: "10.0.8.22"

    db:
      hosts:
        db1:
          ansible_host: 10.0.8.23
          ip_address: "10.0.8.23"

    app:
      hosts:
        app1:
          ansible_host: 10.0.8.24
          ip_address: "10.0.8.24"

    swarm_managers:
      children:
        mgmt: {}

    swarm_workers:
      children:
        cicd: {}
        db: {}
        mntr: {}
        app: {}
